name: Publish release to OSSRH

on:
  push:
    tags:
      - v[0-9].[0-9]+.[0-9]+

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v2
        with:
          key: ${{ hashFiles('pom.xml') }}
          path: ~/.m2/repository
      - name: Set version
        run: |
          mvn_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          git_version=${GITHUB_REF##*/}
          if [[ v$mvn_version != $git_version ]]
          then
            echo Maven version $mvn_version does not match tag $git_version
            exit 1
          fi
      - uses: samuelmeuli/action-maven-publish@v1.4.0
        with:
          gpg_private_key: ${{ secrets.OSSRH_GPG_KEY_ASCII }}
          gpg_passphrase: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
          nexus_username: ${{ secrets.OSSRH_USERNAME }}
          nexus_password: ${{ secrets.OSSRH_PASSWORD }}
