name: Node.js Package

on:
  push:
    branches:
      - 'js-api'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: |
          exec bash # For shopt, see package.json: scripts.protoLoaderGenTypes
          npm ci
          npm run build
          npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
      - run: |
          exec bash # For shopt, see package.json: scripts.protoLoaderGenTypes
          npm ci
          npm run build
          npm test
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
